# Generated by Django 4.0.3 on 2022-04-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='servicesProvided',
            new_name='services_provided',
        ),
    ]
