# Generated by Django 4.0.3 on 2022-04-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_relationship', models.CharField(max_length=50)),
                ('primary_number', models.IntegerField()),
                ('address', models.TextField()),
                ('diagnoses', models.CharField(max_length=1000)),
                ('services_needed', models.CharField(max_length=1000)),
                ('recertification_date', models.CharField(max_length=10)),
                ('summary_of_care_notes', models.TextField()),
                ('visits', models.CharField(max_length=25)),
                ('providers', models.ManyToManyField(to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('was_attended', models.BooleanField(default=False)),
                ('makeup_needed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Summary_of_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('summary_notes', models.TextField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='providers.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.patient')),
            ],
        ),
    ]
