# Generated by Django 4.0.3 on 2022-04-08 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=50)),
                ('guardianName', models.CharField(max_length=50)),
                ('guardianRelationship', models.CharField(max_length=50)),
                ('primaryNumber', models.IntegerField()),
                ('address', models.CharField(max_length=200, verbose_name='Address line 1')),
                ('diagnoses', models.CharField(max_length=1000)),
                ('servicesNeeded', models.CharField(max_length=1000)),
                ('summaryOfCareNotes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
