# Generated by Django 4.0.3 on 2022-04-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='guardianName',
            new_name='guardian_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='guardianRelationship',
            new_name='guardian_relationship',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='primaryNumber',
            new_name='primary_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='servicesNeeded',
            new_name='services_needed',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='summaryOfCareNotes',
            new_name='summary_of_care_notes',
        ),
    ]
