# Generated by Django 4.0.3 on 2022-04-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='services_needed',
        ),
        migrations.AddField(
            model_name='patient',
            name='needs_bt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='needs_ot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='needs_pt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='needs_st',
            field=models.BooleanField(default=False),
        ),
    ]
