# Generated by Django 4.0.3 on 2022-04-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_services_needed_patient_needs_bt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='time',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
