# Generated by Django 4.0.3 on 2022-04-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_visit_date_remove_visit_time_visit_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latitude',
            new_name='LatLng',
        ),
        migrations.RemoveField(
            model_name='address',
            name='longitude',
        ),
    ]
