# Generated by Django 4.0.3 on 2022-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_note_patient_note_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary_of_care',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
